#!/bin/bash

# Function to display a message and exit
function exit_with_error {
    echo "Error: $1"
    exit 1
}

# Default values
twilightflats_folder=''
masterlampflats_folder=''
masterdark_folder=""
lmaps_folder=""
output_folder=""
mode=""

# Parse command-line arguments
for arg in "$@"; do
    case $arg in
        --twilightflats_folder=*)
            twilightflats_folder="${arg#*=}"
            ;;
        --masterdark_folder=*)
            masterdark_folder="${arg#*=}"
            ;;
        --lmaps_folder=*)
            lmaps_folder="${arg#*=}"
            ;;
        --masterlampflats_folder=*)
            masterlampflats_folder="${arg#*=}"
            ;;
        --output_folder=*)
            output_folder="${arg#*=}"
            ;;
        *)
            exit_with_error "Unknown argument: $arg"
            ;;
    esac
done

# Error checking for required arguments
if [[ -z "$twilightflats_folder" || -z "$masterdark_folder" || -z "$lmaps_folder" || -z "$masterlampflats_folder" || -z "$output_folder" ]]; then
    exit_with_error "Usage: $0 --twilightflats_folder=<path> --masterdark_folder=<path> --lmaps_folder=<path> --masterlampflats_folder=<path> --output_folder=<path>"
fi

# Check if the folders exist
if [[ ! -d "$twilightflats_folder" ]]; then
    exit_with_error "Linearity folder '$twilightflats_folder' does not exist."
fi

if [[ ! -d "$masterdark_folder" ]]; then
    exit_with_error "Linearity folder '$masterdark_folder' does not exist."
fi

if [[ ! -d "$lmaps_folder" ]]; then
    exit_with_error "Linearity folder '$lmaps_folder' does not exist."
fi
if [[ ! -d "$masterlampflats_folder" ]]; then
    exit_with_error "Linearity folder '$masterlampflats_folder' does not exist."
fi

if [[ ! -d "$output_folder" ]]; then
    exit_with_error "Output folder '$output_folder' does not exist."
fi

# Define the output file
output_file="$output_folder/flattwilight.sof"

# Check if output file already exists
if [[ -f "$output_file" ]]; then
    read -p "Output file '$output_file' already exists. Overwrite? (y/n): " overwrite_choice
    if [[ "$overwrite_choice" != "y" && "$overwrite_choice" != "Y" ]]; then
        echo "Installation aborted."
        exit 1
    fi
fi

# Create the output file
echo "Creating output file '$output_file'..."
echo " " > "$output_file"

#Fetch linearity files
#Add the linearity map files
echo "$(realpath "$lmaps_folder")/eris_nix_detmon_ir_lg_bpm.fits BP_MAP_NL" >> "$output_file"
echo "$(realpath "$lmaps_folder")/eris_nix_detmon_ir_lg_coeffs_cube.fits COEFFS_CUBE" >> "$output_file"
echo "$(realpath "$lmaps_folder")/eris_nix_detmon_ir_lg_linearity_table.fits DET_LIN_INFO" >> "$output_file"
echo "$(realpath "$lmaps_folder")/eris_nix_detmon_ir_lg_gain_table.fits GAIN_INFO" >> "$output_file"

echo "$(realpath "$masterdark_folder")/master_dark.fits MASTER_DARK_IMG" >> "$output_file"

echo "$(realpath "$masterlampflats_folder")/master_bpm_lamp.fits MASTER_BPM_LAMP" >> "$output_file"


# List the FITS files and extract metadata
temp_file_list="temp_file_list.txt"
find "$(realpath "$twilightflats_folder")" -type f | sort > "$temp_file_list"

# Process each FITS file
while IFS= read -r fits_file; do
          
    object_name=$(dfits $fits_file | fitsort OBJECT |  awk 'NR > 1' | awk '{print $2}')

    if [ "$object_name" == "FLAT,TWILIGHT" ]; then
        echo "$fits_file FLAT_TWILIGHT" >> "$output_file"
    fi
    
done < "$temp_file_list"

# Clean up
rm "$temp_file_list"
echo "Processing complete. Output saved to '$output_file'."

